name: 🏗️ Build Public HTML Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'schemas/**'
      - 'ai-generators/build_public_pages.py'

jobs:
  build-public-pages:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          pip install pandas pyyaml

      - name: 🖨️ Generate public HTML pages
        run: |
          cd ai-generators
          python build_public_pages.py

      - name: 💾 Commit and push generated files (if any)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          FILES_TO_ADD=""
          for f in help.html faqs.html services.html testimonials.html contact.html about.html index.html; do
            if [ -f "$f" ]; then
              FILES_TO_ADD="$FILES_TO_ADD $f"
              echo "✅ Found $f — will commit"
            else
              echo "⚠️ $f not found — skipping"
            fi
          done

          if [ -n "$FILES_TO_ADD" ]; then
            git add $FILES_TO_ADD
            git commit -m "AUTO: Update public HTML pages"
            # 🔑 USE GITHUB_TOKEN TO AUTHENTICATE PUSH
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
            echo "🚀 Successfully pushed updated pages"
          else
            echo "❌ No HTML files to commit. Check earlier logs for errors."
            exit 1
          fi
